name:                haskell-editor
version:             0.1.0.0
github:              ""
license:             BSD3
author:              "Maximilian Medetz"
maintainer:          "maximilian.medetz@gmail.com"
copyright:           "2018 Maximilian Medetz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-editor#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal
- no-buffering-workaround
- mtl

library:
  source-dirs: src

executables:
  haskell-editor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-editor

tests:
  haskell-editor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-editor
